### ISSUE TITLE
frontend: support implicit casting

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1386]
For the TPC-H Q6 query:

```
l_shipdate < date '1994-01-01' + interval '1' year
```

date '1994-01-01' + interval '1' year -> timestamp
l_shipdate is a date

we should support implicit cast from date to timestamp in this case.

**Comment by xiangjinwu** [comment]
Resolved by #3393

However, for comparison between `date` and `timestamp`, it is still implemented directly rather than with implicitly inserted cast expr. This is the same in [PostgreSQL](https://github.com/postgres/postgres/blob/7201cd18627afc64850537806da7f22150d1a83b/src/include/catalog/pg_operator.dat#L2483-L2488).
