### ISSUE TITLE
didn't flush changes to s3 when update row degree

### ISSUE THREAD

**Issue by yuhao-su** [singularity-data/risingwave#2794]
I found a relevant bug. It is that when we update row degree in JoinEntry, we do not flush the changes to S3.

This does not affect inner join, but it affects outer joins and semi/anti join. This explains why these queries are affected.

As for the case of inner join, since it does not make use of row counts, perhaps we can simply not update it as the write is unnecessary...

_Originally posted by @jon-chuang in https://github.com/singularity-data/risingwave/issues/2495#issuecomment-1132447022_

**Comment by yuhao-su** [comment]
Better do it after #2795 to avoid adding things to those that will soon be removed.

**Comment by fuyufjh** [comment]
Is it better to store the degree in memory only?

The motivation is, since every incoming row would populate all the data with the specified join key of the hash table on the other side, we can calculate `degree` within a reasonable time, because there is no IO operation during this.

The advantage of this approach is that we don't need to introduce an additional column `degree`, which makes the hash table more consistent with the index of LookupJoin. 

Alternatively, we can apply this for LookupJoin, but in this way there will be 2 different Join implementations.

**Comment by jon-chuang** [comment]
Yes, we would need to populate both sides of the cache.

This is actually an additional I/O operation since we don't usually need to fetch the update side of the cache.
