### ISSUE TITLE
bug: `interval` doesn't work as expected

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#3003]
**Describe the bug**

```
dev=> select interval '5 days';
ERROR:  Invalid input syntax: Invalid interval 5 days.
dev=> select interval '1 day';
ERROR:  Invalid input syntax: Invalid interval 1 day.
dev=> select interval '1 hour';
ERROR:  Invalid input syntax: Invalid interval 1 hour.
dev=> select interval '1 second';
ERROR:  Invalid input syntax: Invalid interval 1 second.
```

**To Reproduce**

See above.

**Expected behavior**

Tested on PG:

```
dev=# select interval '5 days';
 interval
----------
 5 days
(1 row)

dev=# select interval '1 day';
 interval
----------
 1 day
(1 row)

dev=# select interval '1 hour';
 interval
----------
 01:00:00
(1 row)

dev=# select interval '1 second';
 interval
----------
 00:00:01
(1 row)

```

**Additional context**

N/A

**Comment by xiangjinwu** [comment]
To users, there is a workaround to use the following alternative syntax:
```
select interval '5' day;  -- unit is out of quotes, and is singular rather than plural
select interval '1' day;
select interval '1' hour;
select interval '1' second;
```
Note that we do not support interval literals with multiple fields yet (e.g. `interval '2-03' year to month`).

---

To developers who are willing to help extend the support:

All input format supported by PostgreSQL is [here](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT).

Given the special syntax of an interval literal, it is [parsed in frontend](https://github.com/singularity-data/risingwave/blob/f239a700654fa9aa7ce45f479b53bc4a5a506475/src/frontend/src/binder/expr/value.rs#L65-L115) rather than using a [cast-from-varchar expr evaluated in backend](https://github.com/singularity-data/risingwave/blob/f239a700654fa9aa7ce45f479b53bc4a5a506475/src/expr/src/expr/expr_unary.rs#L94-L104). (Ideally there should be one parsing function that is used by both frontend and backend cast-eval.)

https://github.com/singularity-data/risingwave/blob/f239a700654fa9aa7ce45f479b53bc4a5a506475/src/frontend/src/binder/expr/value.rs#L32-L39
