### ISSUE TITLE
storage: dedup `into_stream_inner` and `into_stream` in StateTableRowIter

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3049]
Looks like the two functions are nearly the same. Any comments cc @wcy-fdu ?

**Comment by skyzh** [comment]
Also memtable iter can use a simple binary search to reduce overhead. It seems that we do a comparison every time when we meet a memtable key.

**Comment by BugenZhao** [comment]
Iterating the whole table/keyspace might be implemented as iterating with a range of `(Unbounded, Unbounded)`. We should reuse the code as much as possible.

For example, maybe we should not prepend the prefix here...
https://github.com/singularity-data/risingwave/blob/001814f0e80acefa4e9ad334b6b14774735b032f/src/storage/src/table/state_table.rs#L158-L168

But do this stuff here instead.
https://github.com/singularity-data/risingwave/blob/001814f0e80acefa4e9ad334b6b14774735b032f/src/storage/src/keyspace.rs#L147-L173

So that we can reuse `Keyspace::iter_with_range` better.

**Comment by skyzh** [comment]
Yes, I agree.
