### ISSUE TITLE
meta: etcd using 16GB memory

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3054]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/4198311/172535052-d4f0603c-0c25-40e9-8726-ab2a879d2f1f.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/4198311/172535110-2990b1a3-85e0-40e0-9d2f-293b6356e397.png">

This is found when @Shmiwy is benchmarking changes in compaction.

We should optimize resource usage 🤣

**Comment by skyzh** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/4198311/172535633-0fc35fef-ceb1-4574-8c59-bfce4220412c.png">

There's completely no warnings during the process. So I guess some components are silently ignoring the errors.

**Comment by zwang28** [comment]
Some observations:

1. Etcd's memory usage spikes (12:35 in figure) right after barrier latency backs to normal (100ms)
2. Shorter barrier latency leads to more new versions. With version size ~ 600KB, 6MB version data is written to etcd per second. Vacuum delete old unused versions every 30 second, that's 30*6MB.

I suspect etcd's compaction just cannot keep up with it. I'm doing some tests.

**Comment by zwang28** [comment]
It turns out there is two issues actually.
### The first issue

etcd space quota exceeded, which leads to error message "etcdserver: mvcc: database space exceeded" in meta node.

<img width="1463" alt="revision_mode" src="https://user-images.githubusercontent.com/70626450/172766503-704dfbef-317e-4aa9-b192-2ce9553c2943.png">


### Fix the first issue

Previously etcd compaction is revision mode and is triggered per 5min(not configurable):
```
            .arg("--auto-compaction-mode")
            .arg("revision")
            .arg("--auto-compaction-retention")
            .arg("100");
```

We can fix it by applying periodic mode:
```
            .arg("--auto-compaction-mode")
            .arg("periodic")
            .arg("--auto-compaction-retention")
            .arg("1m")
```
<img width="1467" alt="periodic_mode" src="https://user-images.githubusercontent.com/70626450/172767483-4e1b183f-695e-41cf-a577-2cdd6bcc3ed0.png">

**Comment by zwang28** [comment]
### The second issue
After fixing issue 1, the etcd memory usage is still increasing. It's caused by https://etcd.io/docs/v3.5/op-guide/maintenance/#raft-log-retention.

### Fix the second issue
By setting a smaller `snapshot-count`, we can limit etcd's memory usage:
```
            .arg("--snapshot-count")
            .arg("100");
```
<img width="1455" alt="snapshot_count_100" src="https://user-images.githubusercontent.com/70626450/172767832-8ea2bccb-5323-454c-8637-08cd34baab44.png">

**Comment by zwang28** [comment]
In summary, the issue is caused by heavy write to etcd, which is caused by frequent checkpoint and large hummock version size.
we can **workaround** this issue by changing etcd's configuration from
```
            .arg("--auto-compaction-mode")
            .arg("revision")
            .arg("--auto-compaction-retention")
            .arg("100");
```
to

```
            .arg("--auto-compaction-mode")
            .arg("periodic")
            .arg("--auto-compaction-retention")
            .arg("1m")
            .arg("--snapshot-count")
            .arg("100");
```

**Comment by skyzh** [comment]
Good work! Let's workaround this in risedev 🤣

**Comment by zwang28** [comment]
> Good work! Let's workaround this in risedev 🤣

Should be aware of performance changes caused by configuration changes...
