### ISSUE TITLE
Meta restart fail due to panic on `keep lease failed, another node has become new leader`

### ISSUE THREAD

**Issue by yezizp2012** [singularity-data/risingwave#3398]
**Describe the bug**
Start Meta with etcd backend and restart it. Meta will panic when starting due to `keep lease failed, another node has become new leader`.

**To Reproduce**
As described.

**Expected behavior**
Meta restart successfully.

**Additional context**

**Comment by yezizp2012** [comment]
Cc @Little-Wallace

**Comment by zwang28** [comment]
@Little-Wallace  I think META_LEADER_KEY should be updated here.
https://github.com/singularity-data/risingwave/blob/ac77464285c34bf6fd5bd02baf4f396585ef3e60/src/meta/src/rpc/server.rs#L186
Because it's checked here
https://github.com/singularity-data/risingwave/blob/ac77464285c34bf6fd5bd02baf4f396585ef3e60/src/meta/src/rpc/server.rs#L229

**Comment by yezizp2012** [comment]
> @Little-Wallace I think META_LEADER_KEY should be updated here.
> 
> https://github.com/singularity-data/risingwave/blob/ac77464285c34bf6fd5bd02baf4f396585ef3e60/src/meta/src/rpc/server.rs#L186
> 
> 
> Because it's checked here
> https://github.com/singularity-data/risingwave/blob/ac77464285c34bf6fd5bd02baf4f396585ef3e60/src/meta/src/rpc/server.rs#L229

Yes, you're right. It should be updated after the check.
