### ISSUE TITLE
batch: Introduce per crate error for batch executors.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3483]

**Comment by ZENOTME** [comment]
I find the executor crate will accept the error from other crates, such as 'ExprError', 'ProstNotFound'... If we include other crate error in crate error, things become complicated... (I don't sure whether it cause a dependence problem
 
So, for covert the other crate error simplified, I use a RwError in executor error. We can use map_err(|e| RwError::from(e)) to convert the other crate error into RwError and store it in executor error.

```
pub enum BatchExecutorError {
    #[error("Unsupported function: {0}")]
    UnsupportedFunction(String),

    #[error("Can't cast {0} to {1}")]
    Cast(&'static str, &'static str),

    #[error("Array error: {0}")]
    Array(#[from] ArrayError),

    #[error(transparent)]
    RwError(#[from] RwError),

    #[error(transparent)]
    Internal(#[from] anyhow::Error),
}

impl From<BatchExecutorError> for RwError {
    fn from(s: BatchExecutorError) -> Self {
        match s {
            BatchExecutorError::RwError(e) => e,
            _ => ErrorCode::BatchExecutorError(Box::new(s)).into(),
        }
    }
}
```

**Comment by liurenjie1024** [comment]
LGTM. But it maybe useful to add meaningful names to errors, for example `Expr(BoxedError)`, `Meta(BoxedError)`.

**Comment by ZENOTME** [comment]
I find a problem: 
I use BatchExecutorError in executor crate and this modification propagate to frontend/query. Because now the result return from executor(DataChunkStream) is Result<_, BatchExector> rather than Result<_,RwError>. Hence something in frontend/query need to modify according it.

I’m not sure whether this is acceptable, and I think we need to decide how to propagate error. (Is a general problem if we want to do per-crate error ?

I can think of two ways: 

![planA drawio](https://user-images.githubusercontent.com/43447882/177147594-2dd003b1-1574-44d4-bc08-c3be98f21f10.png)
In the first way, we just propagate BatchExecutorError. It’s advantage is simple for executor crate. But it will cause modification in other crate (other crate which use executor), and I’m not sure whether it will cause convert complicated when we has many crate and each of them has their per-crate error (Lots of convert work we need do

![planB drawio](https://user-images.githubusercontent.com/43447882/177147695-9024a4c0-cfa8-40c8-9a58-442d49965c29.png)
The second way is convert the ExecutorError into RwError before we propagate it to other crate. Looks ideally well but I’m not sure what complicated thing will introduce  in pratice.

**Comment by liurenjie1024** [comment]
I would vote for the second way, so we will need to add an `BatchError` in `RwError`?
