### ISSUE TITLE
batch: Monitor compute task status.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3834]
Currently we have two grpc apis for task execution creating and monitoring mpp tasks: `CreateTask` and `GetTaskInfo`. We should merge them into one:
```
rpc CreateTask(CreateTaskRequest) return (stream TaskInfoResponse)
```

In this new api, the compute node creates and executes task, and continues report task info to caller, it mainly includes following info:
1. Task status, e.g. pending, running, failed, finished.
2. Task level metrics, e.g. input number of rows and data size from different exchange sources, output number of rows and data size to sinks.

The frontend scheduler needs to response to certain task status, for example when a task failed, it should cancel current query, e.g. abort all running tasks.

**Comment by BowenXiao1999** [comment]
I have draft a PR for this. But I think we need some discussion so cc @fuyufjh.

Now the design is:

We use the streaming GRPC, it's a receiver-sender mode. So the server holds the sender, and once every state change (e.g. task from Running -> Failed), the sever will send a response to the sender so the stream has a new Response to the client. In future may introduce fixed-time metrics collecting from task, just like task input rows/output rows. This info will be collected and displayed in dashboard (**Note: not Grafana** ). 

The thing I want to disucss: 
1. Now each create_task is a unary RPC. After this, we change to all streaming RPC, I' m concerned about too many long-living connections when tasks numbers increase. 

Solution to this: Aggregate task create in frontend, frontend send bunch of tasks to compute node instead of one by one. The effect is almost the same as current: spawn new task for each create_task RPC.

2. The RPC Response now contains the state change + task level metrics. Not sure wether the message is too much. Metrics are send from CN to frontend, and then export to Dashboard. 

@liurenjie1024 designs in this way cuz he thinks if task level metrics are directly collect from CN to Dashboard, then the Dashboard may be complex to impl : It needs query status from FE, metrics status from CN. Sounds reasonable, but I' m not sure cuz I do not start to research on Dashboard yet.

Previously I want to collect metrics just like streaming (using Prometheus), collect metrics in prometheus + grafana (task will be tagged with id when send to CN) and dashboard somehow query it. 

Glad to have more opinions and disscuss on this design.

**Comment by BowenXiao1999** [comment]
Another point is about Dashboard. 

Now the dashboard is bundled with meta. So how should the status in FE been exported to meta? Or we make dashborad a service? Or we build two dashboards (one for FE one for meta)? 

 Consult @skyzh on this but we do not have a good conclusion. 😢

**Comment by liurenjie1024** [comment]
> Now each create_task is a unary RPC. After this, we change to all streaming RPC, I' m concerned about too many long-living connections when tasks numbers increase.

In fact there will only be one connection. The grpc can reuse tcp connection for multiplexing.

> The RPC Response now contains the state change + task level metrics. Not sure wether the message is too much. Metrics are send from CN to frontend, and then export to Dashboard.

I don't think there will be much messages here because we just send update periodically to frontend.

**Comment by liurenjie1024** [comment]
>  Now the dashboard is bundled with meta. So how should the status in FE been exported to meta? Or we make dashborad a service? Or we build two dashboards (one for FE one for meta)?

We just need to have an http endpoint in frontend to expose those to meta. In fact it's not meta,  we just need an http endpoint, and dashboard can send http requests to frontend http endpoint throught ajax api.

**Comment by BowenXiao1999** [comment]
Tracking:
- [ ] Tweak some RPC interface: #4214 
- [ ] Change to streaming RPC

**Comment by liurenjie1024** [comment]
I think we can close this now?
