### ISSUE TITLE
Sqlsmith: Generate Aggregate

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#3858]

**Comment by marvenlee2486** [comment]
My implementation,
Similar to gen_expr, 
we need a type casting (given a output type, we select any agg function that would output it). However, I dun think there is any of this for agg functions in the current codebase (correct me if I am wrong), so I shall implement this.


After having this, certain rule needed to be adhere
1) Aggregate function cannot be nested
2) Expression used inside an Aggregate function can be any columns of bounded relations, but the expression used that is not inside an aggregate function can only involve bounded columns restricted by group by. 
3) If one of the select items is an aggregate function of bounded columns, then all other select items is an aggregate function.
We can have other expression for bounded columns (restricted by group by) and aggregate function of others columns.

As such
Since aggregate function is also expr, 1) and 2) can be implemented by adding a variable inside gen_expr (stating whether it is inside an aggregate function.
If yes, we can choose any columns in bounded relations and we cannot choose aggregate function
If no, we can only choose from columns in bounded columns (Restricted by group by).

as for 3), before selecting expr, we select either one of the two cases and output correspondingly.

**Comment by kwannoel** [comment]
> 3. If one of the select items is an aggregate function of bounded columns, then all other select items is an aggregate function.
We can have other expression for bounded columns (restricted by group by) and aggregate function of others columns.

We can have columns, as long as they are in GROUP BY.
```sql
select count(*), v from t group by v;
```

We can also have literals.
```
select count(*), 1 from t group by v;
```

The condition should be: 
column must appear in the GROUP BY clause or be used in an aggregate function

**Comment by kwannoel** [comment]
> Since aggregate function is also expr, 1) and 2) can be implemented by adding a variable inside gen_expr (stating whether it is inside an aggregate function.
> If yes, we can choose any columns in bounded relations and we cannot choose aggregate function
> If no, we can only choose from columns in bounded columns (Restricted by group by).
> 
> as for 3), before selecting expr, we select either one of the two cases and output correspondingly.

Otherwise these approaches sound OK.

**Comment by marvenlee2486** [comment]
> > 3. If one of the select items is an aggregate function of bounded columns, then all other select items is an aggregate function.
> >    We can have other expression for bounded columns (restricted by group by) and aggregate function of others columns.
> 
> We can have columns, as long as they are in GROUP BY.
> 
> ```sql
> create table t(v int);
> select count(*), v from t group by v;
> ```
> 
> We can also have literals.
> 
> ```sql
> create table t(v int);
> select count(*), 1 from t group by v;
> ```
> 
> The condition should be: column must appear in the GROUP BY clause or be used in an aggregate function

Yaya, that what i mean by other expression for bounded coloumn haha. Thank for making it clearer.
