### ISSUE TITLE
varchar compatibility with PG

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#4092]
**Describe the bug**
```
dev=> CREATE TABLE VARCHAR_TBL(f1 varchar(1));
CREATE_TABLE
dev=> INSERT INTO VARCHAR_TBL (f1) VALUES ('cd');
INSERT 0 1
dev=> INSERT INTO VARCHAR_TBL (f1) VALUES ('c     ');
INSERT 0 1
dev=> select * from VARCHAR_TBL;
   f1   
--------
 c     
 cd
(2 rows)
```
We remark that it should be `c` instead of 
```c(space)(space)(space)(space)(space)```.

**To Reproduce**
Do as above.

**Expected behavior**
```
martin=# CREATE TABLE VARCHAR_TBL(f1 varchar(1));
CREATE TABLE
martin=# INSERT INTO VARCHAR_TBL (f1) VALUES ('cd');
ERROR:  value too long for type character varying(1)
martin=# INSERT INTO VARCHAR_TBL (f1) VALUES ('c     ');
INSERT 0 1
martin=# select * from VARCHAR_TBL;
 f1 
----
 c
(1 row)
```

**Additional context**
Related #4089

**Comment by xiangjinwu** [comment]
> Variable-length character string. **We do not support specifying the maximum length as of now.**
https://www.risingwave.dev/docs/latest/sql-data-types/

In current implementation, `decimal(10, 3)` is rejected but not `varchar(1)`, because this allows many existing queries to run without modification. In those queries, the length limit is required by syntax rather than for its truncating semantic, and is usually a large number.

But if we believe this can be confusing, we can also reject `varchar(1)`.

As for supporting `varchar(n)` type, it would take a much bigger refactor.

**Comment by lmatz** [comment]
>we can also reject varchar(1). As for supporting varchar(n) type, it would take a much bigger refactor.

Makes sense👍.

Guess this is some user-facing doc changes after it gets done?

**Comment by xiangjinwu** [comment]
The user facing doc already says `varchar(n)` is not supported since day 1. We just need to decide how we handle it:
* Reject the query. This ensures correct semantic on `varchar(1)`, but creates more migration cost for users of `varchar(255)`.
* Treat it as `varchar`. This produces unexpected result when limit exceeds, but works seamlessly for use cases that does not prefer the truncation.

Based on discussion in #1274, we thought the no-truncation use cases are majority and chose option 2. Not sure if there are better ways to be both safe and smooth.

**Comment by liurenjie1024** [comment]
> Reject the query. This ensures correct semantic on varchar(1), but creates more migration cost for users of varchar(255).

Vote for this one. Migration cost is better than misbehaving silently.

**Comment by xiangjinwu** [comment]
Because it makes our type system much more simple, and the ability to truncate by type limit is rarely used.

**Comment by fuyufjh** [comment]
IIRC this issue has been discussed and the conclusion is simply ignoring this.

Because we won't be a replacement for PG, so strict compatibility doesn't make sense at all.

**Comment by lmatz** [comment]
`varchar(n)` is not correctly rejected currently. 

I will fix this now.
