### ISSUE TITLE
Sink: writing to mysql table schema mismatch

### ISSUE THREAD

**Issue by nanderstabel** [singularity-data/risingwave#4303]
**Describe the bug**
Mismatch between schema when writing to mysql database.

**To Reproduce**
```
CREATE TABLE t (v1 int, v2 int);
CREATE MATERIALIZED VIEW mv AS SELECT * FROM t;
CREATE SINK s FROM mv WITH (
    sink_type = 'mysql',
    endpoint = '127.0.0.1:3306',
    user = 'root',
    database = 'test',
    table = 't3'
);
INSERT INTO t VALUES (1, 42), (1, 42), (2, 42);
```
results in 
`thread 'tokio-runtime-worker' panicked at 'actor failed: Stream error: Sink error: Sink error: MySQL inner error: Server error: 'ERROR 21S01 (1136): Column count doesn't match value count at row 1'`
in compute node.

**Expected behavior**
No panic + data written to corresponding table in mysql database.

**Comment by skyzh** [comment]
I believe the `CREATE TABLE` statement (you've executed) in MySQL is wrong. You should add a `row_id` column (and all other hidden columns in RisingWave) to MySQL.

As there might be a lot of hidden columns, I'd suggest letting RisingWave create the table and validate the schema inside MySQL before inserting, so that everything should be fine.
