### ISSUE TITLE
SqlSmith Bug Hunt: panic when binding with-CTE containing `expr::Subquery`

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#4404]
**Describe the bug**
with + Exists/IN contribute this bug.

```
create table t1 (x int);
with with_0 as (select * from t1 group by x having EXISTS(select 0.1)) select * from with_0
```

```
create table t1 (x int);
with with_0 as (select * from t1 where EXISTS(select 0.1)) select * from with_0;
```

frontend-4566 log file
[frontend-4566.log](https://github.com/singularity-data/risingwave/files/9249517/frontend-4566.log)

**Additional context**
These statements does not causes panic
If I take out the query inside 'with' and run it, it will not panic.
```
(select * from t1 group by x having EXISTS(select 0.1)
```

If I put the query inside 'with' as a FROM subquery, it will not panic
```
select * from (select * from t1 where EXISTS(select 0.1)) ;
```

Found when implementing this issue https://github.com/singularity-data/risingwave/issues/4296

**Comment by marvenlee2486** [comment]
Additional Investigation
For correlated query,
This is fine 
```
select * from t1 where EXISTS(select * from t2 where t1.x=t2.x)
``` 

This will throw a panic
```
with with_0 as ( select * from t1 where EXISTS(select * from t2 where t1.x=t2.x) ) select * from with_0;
```

**Comment by xiangjinwu** [comment]
`Clone` of `expr::Subquery` was purposely banned, because we thought it would be a short-lived `ExprImpl` variant, and all attempts to clone it are potential bugs that should be avoided:
https://github.com/singularity-data/risingwave/blob/0647d27f7d5c12996d3a04311f717c0c3bfec0ea/src/frontend/src/expr/subquery.rs#L65-L69

However, when adding CTE support, we enabled cloning of most `BoundXxx` structs: #2741

Following this path, the easiest fix is to just derive `Clone` for `expr::Subquery` as well.

(Alternatively, we can plan the CTE into a tree and clone that tree instead. I do not see strong incentive to switch to this solution now.)
