### ISSUE TITLE
Discussion: use local execution mode by default

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#4654]
Because we will focus on serving queries (aka. simple, high-concurrent queries) currently

**Comment by chenzl25** [comment]
I suggest that batch dml should share the same schedule logic (distributed/local) as query.
Currently scheduling dml to one compute node is not enough for the following reason:
- For insert select its input can be complex as arbitrary query.
- For update and delete, it is crucial to support index lookup, otherwise full table scan is unacceptable.

**Comment by fuyufjh** [comment]
> I suggest that batch dml should share the same schedule logic (distributed/local) as query. Currently scheduling dml to one compute node is not enough for the following reason:
> 
> * For insert select its input can be complex as arbitrary query.
> * For update and delete, it is crucial to support index lookup, otherwise full table scan is unacceptable.

Hmmm. Agree, but it's another problem. You may open an issue for that.
