### ISSUE TITLE
Store a column either in pk or value, but not both.

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#588]
But we have to make a special case for numeric as its memcomparable key encoding is different from value encoding which retains trailing 0s after its decimal point.

**Comment by kwannoel** [comment]
> @skyzh  The whole keyspace thing is designed not to decode the key, and only decode the value. **(One exception is decoding pk from MView key)**. Decoding key will add a lot of extra complexity in some executors...

For MView, if we de-duplicate pk and value, various cells in a row will be left empty, since they are already stored in pk.
As a result, after decoding MView key to pk, `pk` needs to be further decoded into their corresponding positions these rows.
This seems to require modifications to executors, to provide them with `pk_indices` / `pk_descs` to know how to chunk `pk` into datums, and know their row positions.

As you mentioned this will involve extra complexity. I was wondering if you had any other ideas in mind, which do not require modification to executor.

(cc @lmatz )

**Comment by lmatz** [comment]
As `StateTable is the interface accessing relational data in KV(StateStore) with encoding.`, I think this dedup thing can be put into `StateTable` so that MV and TopN can both benefit from this.

And `StateTable` is aware of pk's info as it has `_pk_indices: Vec<usize>`, `pk_indices` hasn't been used though.

Still require some modifications to executors as you said, but I guess it will make the logic simpler as we transfer the complexity into `StateTable`.

**Comment by kwannoel** [comment]
> As `StateTable is the interface accessing relational data in KV(StateStore) with encoding.`, I think this dedup thing can be put into `StateTable` so that MV and TopN can both benefit from this.
> 
> And `StateTable` is aware of pk's info as it has `_pk_indices: Vec<usize>`, `pk_indices` hasn't been used though.
> 
> Still require some modifications to executors as you said, but I guess it will make the logic simpler as we transfer the complexity into `StateTable`.

MV uses StateTable, but this only applies for writes.

For reads e.g. `select * from some_mv`, we don't go through MV executor. Rather, we may go through other executors, e.g. `RowSeqScan` executor. That currently uses `CellBasedTableRowIter` to read from storage.

There are two options I can think of from there:
1. Refactor `CellBasedTableRowIter` to be constructed with `pk_indices`, so it can decode pk of cells  which were dedup'ed.
2. Refactor `RowSeqScan` and possibly other executors which read to use `StateTable`. Refactor `StateTable` to use `pk_indices` field to decode too.

Both require a fair amount of changes, so would like to check if I'm on the right track.

(Or did you mean keep dedup only to memtable buffer? :thinking: If that's the case I think that could work, since writes to StateStore will retain original encoding, so no changes to read executors needed).

**Comment by skyzh** [comment]
I would +1 for

```
Refactor CellBasedTableRowIter to be constructed with pk_indices, so it can decode pk of cells which were dedup'ed
```

Or introduce a new set of iterators and state tables that remove pk cells without changing the existing ones?

**Comment by skyzh** [comment]
I'm thinking of add more layers to existing iterators, so that the code will look clean...

* CellBasedTableRowIter: simply scan all items from storage, decode value without decoding pk, and return `<serialized pk, value>` to caller.
* `<SomethingNew>RowIterator`: take input from `CellBasedTableRowIter`, and decode pk. It will need to know how to decode values from serialized keys.
* StateTable: as now.
* `<SomethingNewStateTable>`: use `<SomethingNew>RowIterator` underlying, so that it doesn't need to store pk inside value.

**Comment by skyzh** [comment]
Given a table:

```
col1 (pk) | col2
     1    | 2
```

The original cell based table will store it as:

```
[1, col1] -> 1
[1, col2] -> 2
```

And the new table format will be
```
[1, col2] -> 2
```

Therefore, the new table format will be compatible with the old one, except that we will use information in serialized pk. So I think adding another layer might be a good option.

**Comment by kwannoel** [comment]
> Given a table:
> 
> ```
> col1 (pk) | col2
>      1    | 2
> ```
> 
> The original cell based table will store it as:
> 
> ```
> [1, col1] -> 1
> [1, col2] -> 2
> ```
> 
> And the new table format will be
> 
> ```
> [1, col2] -> 2
> ```
> 
> Therefore, the new table format will be compatible with the old one, except that we will use information in serialized pk to decode some values. So I think adding another layer might be a good option.

Thanks!

**Comment by lmatz** [comment]
Duplicated with tracking issue #3412, close this one.
